name: Build and Test .NET 7

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
          cache: true
          cache-dependency-path: ./SierraSam/packages.lock.json
      - name: Restore Dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: build-artifact
          path: ./*/bin/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Install Postgres ODBC Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y odbc-postgresql
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
          cache: true
          cache-dependency-path: ./SierraSam/packages.lock.json
      - name: Restore Dependencies
        run: dotnet restore --locked-mode
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - name: Run Tests
        run: dotnet test --configuration Release --no-build
