name: SierraSam Build

on: [push]

jobs:
  build-and-test:
    strategy:
        matrix:
            runtime: [win-x64, linux-x64, linux-arm64, osx-x64, osx-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
          cache: true
          cache-dependency-path: ./SierraSam/packages.lock.json
      - name: Restore Dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Install Postgres ODBC Driver
        if: success()
        run: |
          sudo apt-get update
          sudo apt-get install -y odbc-postgresql
      - name: Run Tests
        if: success()
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Publish
        if: success()
        run: |
          dotnet publish \
          --configuration Release \
          --no-build \
          --verbosity normal \
          --runtime ${{ matrix.runtime }} \
          --self-contained true
      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: SierraSam-${{ matrix.runtime }}
          path: ./SierraSam/bin/Release/net7.0/${{ matrix.runtime }}/publish