name: Build and Test .NET 7

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Postgres ODBC Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y odbc-postgresql

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-restore --verbosity normal

      - name: Publish Artifact
        if: success()
        run: |
          dotnet publish -c Release -o ${{ github.workspace }}/publish
          echo "::set-output name=artifact_path::${{ github.workspace }}/publish"

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-publish
          path: ${{ steps.publish.outputs.artifact_path }}
