name: MySQL

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: ./SierraSam/packages.lock.json
      - name: Restore Dependencies
        run: dotnet restore --locked-mode
      - name: Install MySQL ODBC Driver
        if: success()
        run: |
          wget https://dev.mysql.com/get/Downloads/Connector-ODBC/8.2/mysql-connector-odbc_8.2.0-1ubuntu22.04_amd64.deb
          wget https://dev.mysql.com/get/Downloads/MySQL-8.2/mysql-community-client-plugins_8.2.0-1ubuntu22.04_amd64.deb
          sudo dpkg -i mysql-community-client-plugins_8.2.0-1ubuntu22.04_amd64.deb mysql-connector-odbc_8.2.0-1ubuntu22.04_amd64.deb
      - name: Restore Build Artifacts
        uses: actions/cache@v3
        with:
          path: |
            ./*/bin/
            ./*/obj/
          key: linux-x64-build-${{ github.sha }}
      - name: Run Tests
        if: success()
        run: |
          dotnet test \
          --no-build \
          --filter Category=MySql \
          --configuration Release \
          --verbosity normal \
          --logger trx
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test_results
          path: ./**/TestResults/*.trx
          retention-days: 30