name: Oracle

on: workflow_call

env:
  MAJOR_VERSION: 21
  MINOR_VERSION: 12

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: ./SierraSam/packages.lock.json
      - name: Restore Dependencies
        run: dotnet restore --locked-mode
      - name: Install Oracle ODBC Driver
        if: success()
        run: |
          wget "https://download.oracle.com/otn_software/linux/instantclient/${{env.MAJOR_VERSION}}${{env.MINOR_VERSION}}000/instantclient-basiclite-linux.x64-${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.0.0.0dbru.zip"
          wget "https://download.oracle.com/otn_software/linux/instantclient/${{env.MAJOR_VERSION}}${{env.MINOR_VERSION}}000/instantclient-odbc-linux.x64-${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.0.0.0dbru.zip"
          unzip "instantclient-basiclite-linux.x64-${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.0.0.0dbru.zip" -d /opt/oracle
          unzip "instantclient-odbc-linux.x64-${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.0.0.0dbru.zip" -d /opt/oracle
          sudo apt-get update && sudo apt-get install -y glibc-source libaio1
          sudo bash "/opt/oracle/instantclient_${{env.MAJOR_VERSION}}_${{env.MINOR_VERSION}}/odbc_update_ini.sh" "/" "/opt/oracle/instantclient_${{env.MAJOR_VERSION}}_${{env.MINOR_VERSION}}" "Oracle $MAJOR_VERSION ODBC driver" "OracleODBC-$MAJOR_VERSION" "/etc/odbc.ini"
      - name: Run Tests
        if: success()
        env:
          LD_LIBRARY_PATH: "/opt/oracle/instantclient_${{env.MAJOR_VERSION}}_${{env.MINOR_VERSION}}"
        run: |
          dotnet test \
          --no-restore \
          --filter Category=Oracle \
          --configuration Release \
          --verbosity normal \
          --logger trx
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test_results
          path: ./**/TestResults/*.trx
          retention-days: 30